-------------------------------------------------------------------------------
Test set: com.junit5.MathUtilsTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.078 s <<< FAILURE! - in com.junit5.MathUtilsTest
testDivide  Time elapsed: 0.03 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Divide by zero should throw ==> Unexpected exception type thrown ==> expected: <java.lang.NullPointerException> but was: <java.lang.ArithmeticException>
	at com.junit5.MathUtilsTest.testDivide(MathUtilsTest.java:29)
Caused by: java.lang.ArithmeticException: / by zero
	at com.junit5.MathUtilsTest.lambda$0(MathUtilsTest.java:29)
	at com.junit5.MathUtilsTest.testDivide(MathUtilsTest.java:29)

